version: "3.9"
services:
  spicedb:
    image: quay.io/authzed/spicedb
    ports:
      - "127.0.0.1::8080"
      - "127.0.0.1::50051"
      - "127.0.0.1::9090"
    command:
      - 'serve'
      - '--grpc-preshared-key=t0ken'
      - '--datastore-engine=postgres'
      - '--datastore-conn-uri=postgres://spicedb-pg:5432/spicedb?sslmode=disable&user=postgres&password=root'
    depends_on:
      spicedb-pg:
        condition: service_healthy
      spicedb-migrator:
        condition: service_completed_successfully
  spicedb-migrator:
    image: quay.io/authzed/spicedb
    command:
      - 'migrate'
      - 'head'
      - '--datastore-engine'
      - 'postgres'
      - '--datastore-conn-uri'
      - 'postgres://spicedb-pg:5432/spicedb?sslmode=disable&user=postgres&password=root'
    depends_on:
      spicedb-pg:
        condition: service_healthy
  spicedb-pg:
    image: postgres:14
    ports:
      - "127.0.0.1::5432"
    environment:
      POSTGRES_DB: 'spicedb'
      POSTGRES_PASSWORD: 'root'
    healthcheck:
      test: "psql 'postgres://spicedb-pg:5432/spicedb?sslmode=disable&user=postgres&password=root' --quiet --output=/dev/null -c 'SELECT 1;'"
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 10s